### ISSUE TITLE
Scene objects missing for many scenes

### ISSUE THREAD

**Issue by nghiahhnguyen** [SamGalanakis/ChangeDetectionDatasetViewer#1]
This tool works well for Scene 0.
![image](https://user-images.githubusercontent.com/34543734/105453398-a52c2580-5cb2-11eb-88be-d066bad18ba9.png)

However, for other scenes, only one point is loaded for each object.
![image](https://user-images.githubusercontent.com/34543734/105453600-fc31fa80-5cb2-11eb-991d-32c464edb4db.png)

This is the log trace in the terminal:
![image](https://user-images.githubusercontent.com/34543734/105453685-24215e00-5cb3-11eb-8778-391002100458.png)

I followed the instruction in the README file. If there is anything I should try to fix this issue, please advise me.

**Comment by SamGalanakis** [comment]
That's odd, given that it works for you on the first scene. I just tested it on my side and it works. Did you try restarting? The no points found error seems to point to a mismatch between scene and points. Maybe give it a couple of seconds after changing the point cloud (until you see the first extract) before changing the second dropdown, might be causing the issue. Also, make sure you have .las files for all the scenes. Let me know how it goes.

**Comment by nghiahhnguyen** [comment]
I have tried restarting as well as waiting for a couple of seconds before changing the second dropdown. After the points are not loaded in other scenes, I tried loading Scene 0 and the points are loaded normally.

To make sure the data are not faulty, I have tried downloading the data again, as well as using the latest version of this repo.

I have also made sure that all .las files are extracted in both the 2016 and the 2020 folders.

![image](https://user-images.githubusercontent.com/34543734/105605846-ee6e9900-5dc8-11eb-98c4-249152fef4e9.png)

![image](https://user-images.githubusercontent.com/34543734/105605849-f3cbe380-5dc8-11eb-9ea1-4d34c375e8bb.png)

If there is anything else I should do to troubleshoot, please let me know.

Moreover, this is the error that is thrown when I change to a scene that is not Scene 0.
![image](https://user-images.githubusercontent.com/34543734/105606012-68068700-5dc9-11eb-9dc7-1399e6dc1808.png)

**Comment by SamGalanakis** [comment]
Hey, thanks for trying to troubleshoot. It is really hard for me to debug on my end since it works for me, maybe some kind of OS issue (I am using windows) or browser difference. I pushed a couple of changes, namely removing searchability from the dropdowns and adding a check. My hunch is that the dropdown is giving None as input when initially clicked. If it still doesn't work, what you can do is, at the end of the file set debug=True, add a breakpoint in scene changer function. Start the server and try and change scene, it should trigger the breakpoint then you can check the initial value of "point_number", step through and see where it changes to a Nonetype.

**Comment by nghiahhnguyen** [comment]
Thank you very much for the instant help. Originally, I deployed the tool on Linux. I have just tried deploying on Windows but to no avail. I will try following your other suggestion to debug the problem.

**Comment by nghiahhnguyen** [comment]
After some debugging, I found that this function is behaving abnormally:
![image](https://user-images.githubusercontent.com/34543734/105627973-9ab58b80-5e6c-11eb-88ec-7476c9b2e804.png)

The function filters out all points in the point cloud, as can be seen in the log:
![image](https://user-images.githubusercontent.com/34543734/105627966-8ffaf680-5e6c-11eb-978f-e0dfc8216dbf.png)

Can you verify if this is the problem?

**Comment by SamGalanakis** [comment]
The extract area function extracts a cylinder form the given pointcloud around the specific point given. If there are no points within the cylinder, it returns one dummy point. I am fairly certain this function is not the issue as it works for the first scene for you and also I have used it for other applications. I think I found the issue, the way I was loading files assumed that they are all there but I removed something after the fact. Pull and let me know if it works for you and sorry for the hassle!

**Comment by nghiahhnguyen** [comment]
Thank you so much for your help! It is working now. I really appreciate your instant update.

Just a heads-up, the codes on line 40 and 41 might not work at first because the default folder name when I download the data set from Google Drive has "_" in it (e.g., ~/Shrec_change_detection_dataset_public/2016/)

![image](https://user-images.githubusercontent.com/34543734/105650261-d50f3f00-5ee5-11eb-9c2b-78c960cf8ce1.png)

It is a tiny problem, but people might run into it if they do not look at the code.

**Comment by SamGalanakis** [comment]
> Thank you so much for your help! It is working now. I really appreciate your instant update.
> 
> Just a heads-up, the codes on line 40 and 41 might not work at first because the default folder name when I download the data set from Google Drive has "_" in it (e.g., ~/Shrec_change_detection_dataset_public/2016/)
> 
> ![image](https://user-images.githubusercontent.com/34543734/105650261-d50f3f00-5ee5-11eb-9c2b-78c960cf8ce1.png)
> 
> It is a tiny problem, but people might run into it if they do not look at the code.

Great, good catch! Should be working with all paths now.
